### ISSUE TITLE
PDF pages

### ISSUE THREAD

**Issue by Fjandin** [e-conomic/graphicsmagick-stream#14]
I'm trying to convert pdf to jpg, and only 1 page, but seems like I always get all pages even though i specify page 1.

```
gm({
        format: 'jpg',
        page: 1,
        density: 300
    });
```

Is there something i'm missing?

**Comment by NicolaPrenna** [comment]
The attribute page is an array.
try this:
`gm({
        format: 'jpg',
        page: [1,1],
        density: 300
    });`

**Comment by Fjandin** [comment]
Ah yes. Perfect. Thanks 👍
